import type { Scorecard } from "./types";
import { listScorecards, upsertScorecard, getMetrics } from "./store";

/** Public form-API niche leaderboard — beachhead from the plan. */
const SEED: Omit<Scorecard, "createdAt">[] = [
  {
    id: "seed_tally",
    slug: "tally",
    productName: "Tally",
    docsUrl: "https://developers.tally.so",
    niche: "forms",
    jtbd: "Create a form with one email field and submit a sample response via API.",
    jtbdId: "forms-create-submit",
    score: 8.2,
    successRate: 1,
    public: true,
    seeded: true,
    runs: [
      {
        agent: "claude-code",
        success: true,
        failStep: "none",
        durationMs: 14200,
        transcript: [
          "[claude-code] Found API docs + key auth",
          "[claude-code] Created form → submitted response",
          "[claude-code] SUCCESS",
        ],
        notes: "API-first; agents finish without UI.",
      },
      {
        agent: "cursor-agent",
        success: true,
        failStep: "none",
        durationMs: 15800,
        transcript: ["[cursor-agent] Used REST create + submit", "[cursor-agent] SUCCESS"],
        notes: "Clean endpoints.",
      },
      {
        agent: "codex",
        success: true,
        failStep: "none",
        durationMs: 17100,
        transcript: ["[codex] OpenAPI-ish patterns guessed correctly", "[codex] SUCCESS"],
        notes: "Minor field naming friction only.",
      },
    ],
    fixes: [
      {
        priority: 1,
        title: "Publish /llms.txt",
        detail: "Would cut discovery time further for cold-start agents.",
      },
      {
        priority: 2,
        title: "Official agent skill",
        detail: "Codify the create→submit golden path as SKILL.md.",
      },
    ],
  },
  {
    id: "seed_typeform",
    slug: "typeform",
    productName: "Typeform",
    docsUrl: "https://www.typeform.com/developers/",
    niche: "forms",
    jtbd: "Create a form with one email field and submit a sample response via API.",
    jtbdId: "forms-create-submit",
    score: 6.4,
    successRate: 0.67,
    public: true,
    seeded: true,
    runs: [
      {
        agent: "claude-code",
        success: true,
        failStep: "none",
        durationMs: 21000,
        transcript: ["[claude-code] Create API ok", "[claude-code] SUCCESS"],
        notes: "Works with persistence.",
      },
      {
        agent: "cursor-agent",
        success: true,
        failStep: "none",
        durationMs: 24000,
        transcript: ["[cursor-agent] Found Create API", "[cursor-agent] SUCCESS"],
        notes: "Docs dense but usable.",
      },
      {
        agent: "codex",
        success: false,
        failStep: "auth",
        durationMs: 19000,
        transcript: [
          "[codex] Attempted OAuth-style flow",
          "[codex] FAIL @ auth — personal token path under-documented for agents",
        ],
        notes: "Auth ambiguity.",
      },
    ],
    fixes: [
      {
        priority: 1,
        title: "Agent-first auth page",
        detail: "One page: create PAT → header → first create-form call.",
      },
      {
        priority: 2,
        title: "Ship MCP or CLI",
        detail: "Competitors with thinner APIs + CLI win agent recommendations.",
      },
      {
        priority: 3,
        title: "Official agent skill",
        detail: "SKILL.md for create→submit JTBD.",
      },
    ],
  },
  {
    id: "seed_fillout",
    slug: "fillout",
    productName: "Fillout",
    docsUrl: "https://www.fillout.com/help/api",
    niche: "forms",
    jtbd: "Create a form with one email field and submit a sample response via API.",
    jtbdId: "forms-create-submit",
    score: 5.1,
    successRate: 0.33,
    public: true,
    seeded: true,
    runs: [
      {
        agent: "claude-code",
        success: true,
        failStep: "none",
        durationMs: 26000,
        transcript: ["[claude-code] Found submissions API", "[claude-code] SUCCESS (submit only)"],
        notes: "Submit path clearer than create.",
      },
      {
        agent: "cursor-agent",
        success: false,
        failStep: "tool-selection",
        durationMs: 22000,
        transcript: [
          "[cursor-agent] Help center HTML only",
          "[cursor-agent] FAIL @ tool-selection — no OpenAPI",
        ],
        notes: "No machine contract.",
      },
      {
        agent: "codex",
        success: false,
        failStep: "docs",
        durationMs: 18000,
        transcript: ["[codex] FAIL @ docs — scattered help articles"],
        notes: "Agent got lost.",
      },
    ],
    fixes: [
      {
        priority: 1,
        title: "Publish OpenAPI",
        detail: "Agents invent paths without a contract.",
      },
      {
        priority: 2,
        title: "Add /llms.txt",
        detail: "Index the real API pages, not marketing.",
      },
      {
        priority: 3,
        title: "Official agent skill",
        detail: "FirstSkill pack for create→submit.",
      },
    ],
  },
  {
    id: "seed_google_forms",
    slug: "google-forms",
    productName: "Google Forms",
    docsUrl: "https://developers.google.com/forms",
    niche: "forms",
    jtbd: "Create a form with one email field and submit a sample response via API.",
    jtbdId: "forms-create-submit",
    score: 3.8,
    successRate: 0,
    public: true,
    seeded: true,
    runs: [
      {
        agent: "claude-code",
        success: false,
        failStep: "auth",
        durationMs: 28000,
        transcript: [
          "[claude-code] Google Forms API requires OAuth + Cloud project",
          "[claude-code] FAIL @ auth",
        ],
        notes: "High capability, poor unattended AX.",
      },
      {
        agent: "cursor-agent",
        success: false,
        failStep: "auth",
        durationMs: 25000,
        transcript: ["[cursor-agent] FAIL @ auth — OAuth consent screen"],
        notes: "Same blocker.",
      },
      {
        agent: "codex",
        success: false,
        failStep: "discovery",
        durationMs: 20000,
        transcript: ["[codex] Confused Apps Script vs Forms API", "[codex] FAIL @ discovery"],
        notes: "Surface sprawl.",
      },
    ],
    fixes: [
      {
        priority: 1,
        title: "Service-account / API-key style path",
        detail: "Agents cannot complete browser OAuth consent alone.",
      },
      {
        priority: 2,
        title: "Single JTBD quickstart",
        detail: "One create→respond path without Cloud Console archaeology.",
      },
      {
        priority: 3,
        title: "Official agent skill",
        detail: "Even Google-scale docs need a skill for agents.",
      },
    ],
  },
  {
    id: "seed_jotform",
    slug: "jotform",
    productName: "Jotform",
    docsUrl: "https://api.jotform.com/docs/",
    niche: "forms",
    jtbd: "Create a form with one email field and submit a sample response via API.",
    jtbdId: "forms-create-submit",
    score: 7.1,
    successRate: 0.67,
    public: true,
    seeded: true,
    runs: [
      {
        agent: "claude-code",
        success: true,
        failStep: "none",
        durationMs: 16000,
        transcript: ["[claude-code] API key header clear", "[claude-code] SUCCESS"],
        notes: "Legacy but agent-usable.",
      },
      {
        agent: "cursor-agent",
        success: true,
        failStep: "none",
        durationMs: 17500,
        transcript: ["[cursor-agent] SUCCESS"],
        notes: "OK.",
      },
      {
        agent: "codex",
        success: false,
        failStep: "error-recovery",
        durationMs: 21000,
        transcript: [
          "[codex] Form create payload mismatch",
          "[codex] FAIL @ error-recovery — opaque error body",
        ],
        notes: "Errors not agent-friendly.",
      },
    ],
    fixes: [
      {
        priority: 1,
        title: "Structured error codes",
        detail: "Return remediation strings agents can act on.",
      },
      {
        priority: 2,
        title: "Official agent skill",
        detail: "Freeze a known-good create payload in SKILL.md.",
      },
    ],
  },
  {
    id: "seed_paperform",
    slug: "paperform",
    productName: "Paperform",
    docsUrl: "https://paperform.co/help/articles/paperform-api/",
    niche: "forms",
    jtbd: "Create a form with one email field and submit a sample response via API.",
    jtbdId: "forms-create-submit",
    score: 4.2,
    successRate: 0.33,
    public: true,
    seeded: true,
    runs: [
      {
        agent: "claude-code",
        success: false,
        failStep: "docs",
        durationMs: 23000,
        transcript: ["[claude-code] Help article, limited create examples", "[claude-code] FAIL @ docs"],
        notes: "Thin create docs.",
      },
      {
        agent: "cursor-agent",
        success: true,
        failStep: "none",
        durationMs: 27000,
        transcript: ["[cursor-agent] Used submissions endpoints", "[cursor-agent] partial SUCCESS"],
        notes: "Submit > create.",
      },
      {
        agent: "codex",
        success: false,
        failStep: "tool-selection",
        durationMs: 19000,
        transcript: ["[codex] FAIL @ tool-selection — no OpenAPI"],
        notes: "No contract.",
      },
    ],
    fixes: [
      {
        priority: 1,
        title: "OpenAPI + create-form example",
        detail: "Agents need a create path, not only submissions.",
      },
      {
        priority: 2,
        title: "CLI or MCP",
        detail: "Catch up to Tally-class AX.",
      },
      {
        priority: 3,
        title: "Official agent skill",
        detail: "FirstSkill pack closes the gap fast.",
      },
    ],
  },
  {
    id: "seed_feathery",
    slug: "feathery",
    productName: "Feathery",
    docsUrl: "https://docs.feathery.io/",
    niche: "forms",
    jtbd: "Create a form with one email field and submit a sample response via API.",
    jtbdId: "forms-create-submit",
    score: 5.8,
    successRate: 0.33,
    public: true,
    seeded: true,
    runs: [
      {
        agent: "claude-code",
        success: true,
        failStep: "none",
        durationMs: 20000,
        transcript: ["[claude-code] Docs site structured", "[claude-code] SUCCESS"],
        notes: "Decent DX.",
      },
      {
        agent: "cursor-agent",
        success: false,
        failStep: "api-call",
        durationMs: 24000,
        transcript: ["[cursor-agent] FAIL @ api-call — SDK vs REST ambiguity"],
        notes: "Surface confusion.",
      },
      {
        agent: "codex",
        success: false,
        failStep: "auth",
        durationMs: 18000,
        transcript: ["[codex] FAIL @ auth"],
        notes: "Key setup friction.",
      },
    ],
    fixes: [
      {
        priority: 1,
        title: "REST-first JTBD quickstart",
        detail: "Agents prefer HTTP examples over SDK installs mid-task.",
      },
      {
        priority: 2,
        title: "Official agent skill",
        detail: "Skill should pick REST and freeze field names.",
      },
    ],
  },
  {
    id: "seed_formspree",
    slug: "formspree",
    productName: "Formspree",
    docsUrl: "https://help.formspree.io/hc/en-us",
    niche: "forms",
    jtbd: "Create a form with one email field and submit a sample response via API.",
    jtbdId: "forms-create-submit",
    score: 6.0,
    successRate: 0.67,
    public: true,
    seeded: true,
    runs: [
      {
        agent: "claude-code",
        success: true,
        failStep: "none",
        durationMs: 12000,
        transcript: ["[claude-code] Simple POST endpoint", "[claude-code] SUCCESS"],
        notes: "Submit is trivial.",
      },
      {
        agent: "cursor-agent",
        success: true,
        failStep: "none",
        durationMs: 11000,
        transcript: ["[cursor-agent] SUCCESS"],
        notes: "Good for submit JTBD.",
      },
      {
        agent: "codex",
        success: false,
        failStep: "docs",
        durationMs: 15000,
        transcript: [
          "[codex] Help center maze",
          "[codex] FAIL @ docs — create-form not first-class for agents",
        ],
        notes: "Create vs endpoint form mismatch.",
      },
    ],
    fixes: [
      {
        priority: 1,
        title: "Clarify create vs endpoint forms",
        detail: "Agents need an explicit path for programmatic form creation.",
      },
      {
        priority: 2,
        title: "Official agent skill",
        detail: "Document the exact POST body agents should use.",
      },
    ],
  },
];

export async function ensureSeedScorecards(): Promise<void> {
  const existing = await listScorecards();
  const have = new Set(existing.map((s) => s.id));
  const now = new Date().toISOString();
  for (const seed of SEED) {
    if (have.has(seed.id)) continue;
    await upsertScorecard({ ...seed, createdAt: now });
  }
  // metrics.json is created on first getMetrics() with launchedAt + killAt
  await getMetrics();
}
